FROM node:13.12.0-alpine3.10 as build-app

RUN mkdir /app
WORKDIR /app
COPY ./package.json /tmp/package.json
RUN cp /tmp/package.json /app/package.json
RUN npm install
RUN npm build

FROM nginx:1.17-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]