FROM node:13.12.0-alpine3.10 as build
RUN mkdir /app
WORKDIR /app
COPY ./package.json /tmp/package.json
RUN cp /tmp/package.json /app/package.json
RUN npm install
COPY . /app
RUN npm run build

FROM nginx:1.17-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 9080
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]