"""empty message

Revision ID: 13b79bc79e37
Revises: 
Create Date: 2020-04-09 07:30:03.131731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b79bc79e37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('random_data', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_data_model')
    # ### end Alembic commands ###
